server:
  port: 8080

spring:
  application:
    name: tavern-maingate
# Redis数据库索引（默认为0）
  redis:
    database: 0
    host: 119.3.19.171
    port: 6380
    password: tuozuo
zuul:
  routes:
    tavern-authority:
      path: /tuozuo/auth/v1/**
      url: http://127.0.0.1:8081/
      stripPrefix: false
    tavern-shuiruyi:
      path: /tuozuo/shuiruyi/v1/**
      url: http://127.0.0.1:8083/
      stripPrefix: false
    tavern-xinruyi:
      path: /tuozuo/xinruyi/v1/**
      url: http://127.0.0.1:8084/
      stripPrefix: false
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  servlet-path: /

#tavern.security.jwt.secret: tavern
