server:
  port: 8080

spring:
  application:
    name: tavern-maingate

zuul:
  routes:
    tavern-authority:
      path: /tuozuo/auth/v1/**
      url: http://127.0.0.1:8081/
      stripPrefix: false
    tavern-shuiruyi:
      path: /tuozuo/shuiruyi/v1/**
      url: http://127.0.0.1:8070/
      stripPrefix: false
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000

tavern.security.jwt.secret: tavern
