server:
  port: 8084

tavern.security.jwt.secret: tavern

def.user.switch: false

mybatis-plus:
  # MyBatis Mapper所对应的XML文件位置
  mapper-locations: classpath*:mapper/*Mapper.xml

# 数据源
spring:
  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: y2iaciej
    url: jdbc:mysql://119.3.19.171:3306/xinruyi?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    max-idle: 0
    max-wait: 10000
    min-idle: 1
    initial-size: 2
  application:
    name: tavern-xinruyi