server:
  port: 8181

tavern.security.jwt.secret: tavern

mybatis-plus:
  # MyBatis Mapper所对应的XML文件位置
  mapper-locations: classpath*:mapper/*Mapper.xml

# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1233Trip_mysql
    url: jdbc:mysql://127.0.0.1:3306/auth?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    max-idle: 5
    max-wait: 10000
    min-idle: 1
    initial-size: 5
  application:
    name: tavern-shuiruyi