server:
  port: 8081

spring:
  application:
    name: tavern-authority

# Redis数据库索引（默认为0）
  redis:
    database: 0
    host: 119.3.19.171
    port: 6380
    password: tuozuo
# 数据源
  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: y2iaciej
    url: jdbc:mysql://119.3.19.171:3306/auth?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    max-idle: 5
    max-wait: 10000
    min-idle: 1
    initial-size: 5
wx:
  miniapp:
    configs:
        - appID: #微信小程序的appid
          secret: #微信小程序的Secret
#          token: #微信小程序消息服务器配置的token
#          aesKey: #微信小程序消息服务器配置的EncodingAESKey
          msgDataFormat: JSON